"""Declarative base and shared column mixins.

Every table in this project inherits from `Base`, so its `MetaData` is the
single source of truth for Alembic autogenerate. No domain tables live here.
"""

from sqlalchemy import MetaData, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from ulid import ULID

# Deterministic constraint and index names. Without them PostgreSQL invents
# names, and Alembic cannot reliably drop or alter what it cannot name.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# A ULID in canonical Crockford base32 form is always 26 characters.
ULID_LENGTH = 26


def new_ulid() -> str:
    """Return a fresh ULID as a canonical 26-character string."""
    return str(ULID())


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class ULIDPrimaryKeyMixin:
    """Add a ULID string primary key generated by the application.

    IDs are created client-side so that a new entity can be referenced before
    it is flushed, and they stay time-sortable and opaque to API consumers.
    """

    id: Mapped[str] = mapped_column(String(ULID_LENGTH), primary_key=True, default=new_ulid)
