"""Tests for `app.services.snapshot`.

The snapshot's whole value is that what comes back out is what went in, so what
is tested here is the codec and the payload-path derivation — the two pure
halves. No database: the codec is driven straight off the SQLAlchemy table
metadata, which is exactly how `save` and `load` use it.

The distinction the tests care most about is SQL NULL versus the JSON literal
`null`. Both read back from psycopg as Python `None`, both exist in the live
catalogue (`motorbikes.suggestion` holds SQL NULLs, `motorbike_specs
.source_hints` holds a JSON `null`), and `WHERE col IS NULL` matches only one
of them — so a codec that collapses them silently changes the data.
"""

import gzip
import json
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path

import pytest

from app.db.models.chunk import Chunk
from app.db.models.manufacturer import Manufacturer
from app.db.models.motorbike import Motorbike, MotorbikeStatus
from app.db.models.motorbike_image import ImageStatus, MotorbikeImage
from app.db.models.motorbike_spec import MotorbikeSpec, SpecKind
from app.db.models.source_document import SourceDocument, SourceType
from app.services import image_service, snapshot

MOTORBIKE_ID = "01JZZH0K3QZ8V9W4M8F7Q2R5T1"
DOCUMENT_ID = "01JZZH0K3QZ8V9W4M8F7Q2R5T2"
IMAGE_ID = "01JZZH0K3QZ8V9W4M8F7Q2R5T3"
CHUNK_ID = "01JZZH0K3QZ8V9W4M8F7Q2R5T4"
MANUFACTURER_ID = "01JZZH0K3QZ8V9W4M8F7Q2R5T5"

FETCHED_AT = datetime(2026, 8, 30, 12, 30, 45, 123456, tzinfo=UTC)


def _motorbike_row(**overrides: object) -> dict[str, object]:
    """A `motorbikes` row as `session.stream(...).mappings()` yields it."""
    row: dict[str, object] = {
        "id": MOTORBIKE_ID,
        "query_name": "Suzuki GSR600",
        "slug": "suzuki/gsr600/2006-2011",
        "manufacturer_id": MANUFACTURER_ID,
        "buildingline": "GSR",
        "model_name": "GSR600",
        "year_from": 2006,
        "year_to": 2011,
        "suggestion": {"raw": "Suzuki GSR600"},
        "type_codes": ["WVB9"],
        "variants": [],
        "status": MotorbikeStatus.APPROVED,
        "created_at": FETCHED_AT,
        "updated_at": FETCHED_AT,
        # Only present because `suggestion`, `type_codes` and `variants` are
        # JSON columns; `_read_table` adds one flag per JSON column.
        snapshot.sql_null_label("suggestion"): False,
        snapshot.sql_null_label("type_codes"): False,
        snapshot.sql_null_label("variants"): False,
    }
    row.update(overrides)
    return row


def _round_trip(table: object, row: dict[str, object]) -> dict[str, object]:
    """Encode, serialise through real JSON, then decode — as the archive does."""
    encoded = snapshot.encode_row(table, row)  # type: ignore[arg-type]
    reloaded = json.loads(json.dumps(encoded))
    return snapshot.decode_row(table, reloaded)  # type: ignore[arg-type]


# --- which columns travel ------------------------------------------------


def test_computed_columns_are_not_exported() -> None:
    """`chunks.text_tsv` is generated by PostgreSQL and rejects an INSERT."""
    names = {column.name for column in snapshot.exported_columns(Chunk.__table__)}

    assert "text_tsv" not in names
    assert {"id", "text", "embedding", "sequence"} <= names


def test_json_column_names_finds_the_jsonb_columns() -> None:
    assert snapshot.json_column_names(Motorbike.__table__) == frozenset(
        {"suggestion", "type_codes", "variants"}
    )


# --- scalar types --------------------------------------------------------


def test_enum_is_archived_as_its_value_and_decoded_back_to_the_member() -> None:
    encoded = snapshot.encode_row(Motorbike.__table__, _motorbike_row())

    assert encoded["status"] == "approved"
    assert _round_trip(Motorbike.__table__, _motorbike_row())["status"] is (
        MotorbikeStatus.APPROVED
    )


def test_timestamps_keep_their_microseconds_and_offset() -> None:
    decoded = _round_trip(Motorbike.__table__, _motorbike_row())

    assert decoded["created_at"] == FETCHED_AT


def test_numeric_columns_round_trip_as_decimals_not_floats() -> None:
    """A JSON float would turn `48.5` into a binary approximation."""
    row = {
        "id": "01JZZH0K3QZ8V9W4M8F7Q2R5T6",
        "motorbike_id": MOTORBIKE_ID,
        "kind": SpecKind.VERIFIED,
        "category": "naked",
        "engine_cc": 599,
        "cylinders": 4,
        "power_kw": Decimal("72.8"),
        "torque_nm": Decimal("63.1"),
        "wet_weight_kg": Decimal("212.5"),
        "seat_height_mm": 785,
        "tank_capacity_l": Decimal("16.5"),
        "top_speed_kmh": 220,
        "abs": False,
        "a2_eligible": False,
        "price_band": "mid",
        "msrp_eur": 6500,
        "extra": {},
        "source_hints": None,
        "extracted_at": FETCHED_AT,
        snapshot.sql_null_label("extra"): False,
        # A JSON `null`, not a SQL NULL — the live catalogue has one of these.
        snapshot.sql_null_label("source_hints"): False,
    }

    encoded = snapshot.encode_row(MotorbikeSpec.__table__, row)
    decoded = _round_trip(MotorbikeSpec.__table__, row)

    assert encoded["power_kw"] == "72.8"
    assert decoded["power_kw"] == Decimal("72.8")
    assert decoded["tank_capacity_l"] == Decimal("16.5")


# --- embeddings ----------------------------------------------------------


def test_embedding_round_trips_exactly() -> None:
    """The column is pgvector `float4`, so float32 packing is lossless."""
    embedding = [0.0, 1.0, -0.5, 0.25, 3.4028234663852886e38]
    row = {
        "id": CHUNK_ID,
        "source_document_id": DOCUMENT_ID,
        "motorbike_id": MOTORBIKE_ID,
        "sequence": 0,
        "text": "The GSR600 is regarded as a friendly first big bike.",
        "heading_path": "Suzuki GSR600 > Reception",
        "page_number": None,
        "embedding": embedding,
        "embedding_model": "openai/text-embedding-3-small",
        "embedding_dimensions": 1536,
    }

    encoded = snapshot.encode_row(Chunk.__table__, row)
    decoded = _round_trip(Chunk.__table__, row)

    # Base64 of float32, not a JSON array of decimal literals.
    assert isinstance(encoded["embedding"][snapshot.VECTOR_KEY], str)
    assert decoded["embedding"] == embedding


def test_a_missing_embedding_stays_null() -> None:
    row = {
        "id": CHUNK_ID,
        "source_document_id": DOCUMENT_ID,
        "motorbike_id": MOTORBIKE_ID,
        "sequence": 0,
        "text": "Not embedded yet.",
        "heading_path": None,
        "page_number": None,
        "embedding": None,
        "embedding_model": None,
        "embedding_dimensions": None,
    }

    assert _round_trip(Chunk.__table__, row)["embedding"] is None


def test_a_corrupt_embedding_payload_is_reported() -> None:
    with pytest.raises(snapshot.SnapshotError, match="not a float32 sequence"):
        snapshot.decode_row(
            Chunk.__table__,
            {"id": CHUNK_ID, "embedding": {snapshot.VECTOR_KEY: "AAA="}},
        )


# --- SQL NULL versus JSON null -------------------------------------------


def test_sql_null_json_column_is_omitted_from_the_insert() -> None:
    """Omission is the only way to get a real SQL NULL past SQLAlchemy's JSON type."""
    row = _motorbike_row(suggestion=None, **{snapshot.sql_null_label("suggestion"): True})

    encoded = snapshot.encode_row(Motorbike.__table__, row)
    decoded = _round_trip(Motorbike.__table__, row)

    assert encoded["suggestion"] is None
    assert "suggestion" not in decoded


def test_json_null_json_column_is_inserted_as_none() -> None:
    """Python `None` is what SQLAlchemy renders as the JSON literal `null`."""
    row = _motorbike_row(suggestion=None, **{snapshot.sql_null_label("suggestion"): False})

    encoded = snapshot.encode_row(Motorbike.__table__, row)
    decoded = _round_trip(Motorbike.__table__, row)

    assert encoded["suggestion"] == {snapshot.JSON_NULL_KEY: True}
    assert "suggestion" in decoded
    assert decoded["suggestion"] is None


def test_a_null_json_column_without_a_flag_is_treated_as_sql_null() -> None:
    """The conservative reading, for a row not produced by `_read_table`."""
    row = _motorbike_row(suggestion=None)
    del row[snapshot.sql_null_label("suggestion")]

    assert snapshot.encode_row(Motorbike.__table__, row)["suggestion"] is None


def test_insert_groups_separates_the_two_null_kinds() -> None:
    """`executemany` needs one uniform key set per statement."""
    rows = [
        snapshot.encode_row(Motorbike.__table__, _motorbike_row()),
        snapshot.encode_row(
            Motorbike.__table__,
            _motorbike_row(
                id="01JZZH0K3QZ8V9W4M8F7Q2R5T7",
                slug="other",
                suggestion=None,
                **{snapshot.sql_null_label("suggestion"): True},
            ),
        ),
    ]

    groups = snapshot.insert_groups(Motorbike.__table__, rows)

    assert len(groups) == 2
    assert {len(group) for group in groups} == {1}
    assert {tuple(sorted(row)) for group in groups for row in group} == {
        tuple(sorted(rows[0])),
        tuple(sorted(set(rows[1]) - {"suggestion"})),
    }
    # Every group is internally uniform, which is the property that matters.
    for group in groups:
        assert len({tuple(sorted(row)) for row in group}) == 1


# --- schema drift --------------------------------------------------------


def test_a_column_missing_from_the_archive_falls_back_to_the_database_default() -> None:
    """What lets a snapshot survive an additive migration."""
    payload = snapshot.encode_row(Motorbike.__table__, _motorbike_row())
    del payload["buildingline"]

    decoded = snapshot.decode_row(Motorbike.__table__, payload)

    assert "buildingline" not in decoded
    assert decoded["model_name"] == "GSR600"


def test_a_column_the_schema_no_longer_has_is_refused() -> None:
    """Silently dropping archived data would be worse than refusing to load."""
    payload = snapshot.encode_row(Motorbike.__table__, _motorbike_row())
    payload["retired_column"] = "value"

    with pytest.raises(snapshot.SnapshotError, match="retired_column"):
        snapshot.decode_row(Motorbike.__table__, payload)


# --- payload paths -------------------------------------------------------


def test_collect_payload_paths_covers_originals_variants_and_logos() -> None:
    """Variants are computed from `image_service`, never stored, so they cannot drift."""
    raw_path = f"sources/{MOTORBIKE_ID}/{DOCUMENT_ID}.html"
    paths = snapshot.collect_payload_paths(
        {
            SourceDocument.__tablename__: [{"raw_path": raw_path}],
            MotorbikeImage.__tablename__: [
                {
                    "id": IMAGE_ID,
                    "motorbike_id": MOTORBIKE_ID,
                    "original_path": f"motorbikes/{MOTORBIKE_ID}/{IMAGE_ID}_original.jpg",
                }
            ],
            Manufacturer.__tablename__: [{"logo_path": "manufacturers/suzuki.webp"}],
        }
    )

    assert paths.data == (raw_path,)
    for variant in image_service.VARIANT_WIDTHS:
        assert image_service.variant_path(MOTORBIKE_ID, IMAGE_ID, variant) in paths.media
    assert f"motorbikes/{MOTORBIKE_ID}/{IMAGE_ID}_original.jpg" in paths.media
    assert "manufacturers/suzuki.webp" in paths.media


def test_collect_payload_paths_skips_a_manufacturer_without_a_logo() -> None:
    paths = snapshot.collect_payload_paths({Manufacturer.__tablename__: [{"logo_path": None}]})

    assert paths.media == ()


def test_duplicate_document_paths_are_copied_once() -> None:
    row = {"raw_path": f"sources/{MOTORBIKE_ID}/{DOCUMENT_ID}.html"}

    paths = snapshot.collect_payload_paths({SourceDocument.__tablename__: [row, dict(row)]})

    assert len(paths.data) == 1


@pytest.mark.parametrize("unsafe", ["/etc/passwd", "../../etc/passwd", "sources/../../escape"])
def test_a_payload_path_cannot_escape_the_data_directory(unsafe: str, tmp_path: Path) -> None:
    """A snapshot is a file the user may have received; it must not write anywhere."""
    report = snapshot.SnapshotReport()

    with pytest.raises(snapshot.SnapshotError, match="unsafe payload path"):
        snapshot._copy_out([unsafe], tmp_path, tmp_path / "out", compress=True, report=report)


# --- the archive's payload trees -----------------------------------------


def test_source_payloads_are_gzipped_out_and_gunzipped_back(tmp_path: Path) -> None:
    live = tmp_path / "live"
    archive = tmp_path / "archive"
    restored = tmp_path / "restored"
    relative = f"sources/{MOTORBIKE_ID}/{DOCUMENT_ID}.html"
    payload = b"<html><body><p>raw</p></body></html>" * 100
    (live / relative).parent.mkdir(parents=True)
    (live / relative).write_bytes(payload)
    report = snapshot.SnapshotReport()

    written = snapshot._copy_out([relative], live, archive, compress=True, report=report)
    read_back = snapshot._copy_in(archive, restored, decompress=True, report=report)

    assert written == read_back == 1
    assert gzip.decompress((archive / (relative + snapshot.GZIP_SUFFIX)).read_bytes()) == payload
    assert (restored / relative).read_bytes() == payload
    assert report.missing_files == []


def test_images_travel_verbatim(tmp_path: Path) -> None:
    """WebP and JPEG do not compress twice, so they are copied as-is."""
    live = tmp_path / "live"
    archive = tmp_path / "archive"
    restored = tmp_path / "restored"
    relative = f"motorbikes/{MOTORBIKE_ID}/{IMAGE_ID}_thumb.webp"
    payload = b"RIFF\x00\x00\x00\x00WEBPVP8 fake"
    (live / relative).parent.mkdir(parents=True)
    (live / relative).write_bytes(payload)
    report = snapshot.SnapshotReport()

    snapshot._copy_out([relative], live, archive, compress=False, report=report)
    snapshot._copy_in(archive, restored, decompress=False, report=report)

    assert (archive / relative).read_bytes() == payload
    assert (restored / relative).read_bytes() == payload


def test_a_referenced_file_that_is_not_on_disk_is_reported_not_fatal(tmp_path: Path) -> None:
    """An image whose download failed must not make the catalogue unsnapshottable."""
    report = snapshot.SnapshotReport()

    written = snapshot._copy_out(
        ["sources/gone.html"], tmp_path / "live", tmp_path / "archive", compress=True, report=report
    )

    assert written == 0
    assert report.missing_files == ["sources/gone.html"]


# --- the manifest --------------------------------------------------------


def _write_manifest(directory: Path, **overrides: object) -> Path:
    manifest = {
        "snapshot_version": snapshot.SNAPSHOT_VERSION,
        "created_at": FETCHED_AT.isoformat(),
        "embedding_model": "openai/text-embedding-3-small",
        "embedding_dimensions": 1536,
        "tables": {"motorbikes": 1},
        "data_files": 0,
        "media_files": 0,
        "missing_files": [],
    }
    manifest.update(overrides)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / snapshot.MANIFEST_NAME
    path.write_text(json.dumps(manifest))
    return path


def test_read_manifest_accepts_a_matching_archive(tmp_path: Path) -> None:
    _write_manifest(tmp_path)

    assert snapshot.read_manifest(tmp_path)["tables"] == {"motorbikes": 1}


def test_read_manifest_reports_a_directory_that_holds_no_snapshot(tmp_path: Path) -> None:
    with pytest.raises(snapshot.SnapshotError, match="No snapshot at"):
        snapshot.read_manifest(tmp_path)


def test_read_manifest_refuses_a_future_format(tmp_path: Path) -> None:
    _write_manifest(tmp_path, snapshot_version=snapshot.SNAPSHOT_VERSION + 1)

    with pytest.raises(snapshot.SnapshotError, match="cannot be read by this build"):
        snapshot.read_manifest(tmp_path)


def test_read_manifest_refuses_a_dimension_mismatch(tmp_path: Path) -> None:
    """Loading 768-wide embeddings into a 1536-wide column must fail up front."""
    _write_manifest(tmp_path, embedding_dimensions=768)

    with pytest.raises(snapshot.SnapshotError, match="768-dimensional"):
        snapshot.read_manifest(tmp_path)


def test_source_type_and_image_status_enums_survive_the_round_trip() -> None:
    """Both tables carry a native PostgreSQL enum; neither may decay to a string."""
    document = _round_trip(
        SourceDocument.__table__,
        {
            "id": DOCUMENT_ID,
            "motorbike_id": MOTORBIKE_ID,
            "source_type": SourceType.WIKIPEDIA,
            "source_url": "https://en.wikipedia.org/wiki/Suzuki_GSR600",
            "source_title": "Suzuki GSR600",
            "raw_path": f"sources/{MOTORBIKE_ID}/{DOCUMENT_ID}.html",
            "content_markdown": "# Suzuki GSR600",
            "fetched_at": FETCHED_AT,
            "created_at": FETCHED_AT,
        },
    )
    image = _round_trip(
        MotorbikeImage.__table__,
        {
            "id": IMAGE_ID,
            "motorbike_id": MOTORBIKE_ID,
            "source_url": "https://upload.wikimedia.org/gsr600.jpg",
            "attribution": "CC BY-SA 3.0",
            "status": ImageStatus.PENDING,
            "original_path": f"motorbikes/{MOTORBIKE_ID}/{IMAGE_ID}_original.jpg",
            "created_at": FETCHED_AT,
        },
    )

    assert document["source_type"] is SourceType.WIKIPEDIA
    assert image["status"] is ImageStatus.PENDING
