/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is alive.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether PostgreSQL is reachable; 503 when it is not.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Create an account and return it, without signing the caller in.
         *
         *     No session is created here on purpose: the SPA chains a login call, so there
         *     is exactly one place where cookies are issued.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Authenticate, create a session and set the session and CSRF cookies.
         *
         *     The failure message names neither the username nor the password: which of
         *     the two was wrong is not the caller's business.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Delete the session row and clear both cookies.
         *
         *     Requires the session cookie and a matching `X-CSRF-Token` header: signing
         *     somebody out is a state change, so it is not exempt from CSRF protection.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current account
         * @description Return the signed-in account, with the role read fresh from the database.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to server-sent events
         * @description Open the notification stream for the signed-in account.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the catalogue
         * @description Return one page of approved models, filtered and sorted.
         *
         *     Comma-separated members of one filter are OR-ed, different filters are
         *     AND-ed. A stated specification bound drops models whose verified value is
         *     unknown (a missing number cannot support a claim), while unfiltered browsing
         *     keeps them — the pinned NULL-spec browse rule.
         */
        get: operations["list_catalogue_models_api_catalogue_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue-models/{motorbike_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a catalogue model
         * @description Return one approved model with its specification, prose, sources and images.
         */
        get: operations["get_catalogue_model_api_catalogue_models__motorbike_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the messages of one consultation
         * @description Return one page of a consultation's timeline, oldest message first.
         *
         *     The page is cut from the timeline in the route: `chat_service.list_messages`
         *     loads a whole conversation in one query — a bounded, per-account amount of
         *     text the agent loop replays in full anyway — so paging here keeps that one
         *     pinned ordering as the single source of truth instead of duplicating it in a
         *     second, paginated query. `meta.totalCount` stays the length of the whole
         *     timeline, so the SPA can walk pages.
         */
        get: operations["list_chat_messages_api_chat_messages_get"];
        put?: never;
        /**
         * Send a message to the advisor
         * @description Persist the customer's message and start the advisor's answer.
         *
         *     The body arrives stripped, non-empty and bounded from the request schema —
         *     `chat_service.append_user_message` stores it verbatim and names the
         *     consultation from it when it is still unnamed.
         *
         *     The stale-turn check comes first, because its refusal is a refusal of the
         *     message: an in-flight turn built its context before this request arrived, so
         *     a message stored next to it would never be answered.
         */
        post: operations["create_chat_message_api_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the signed-in account's consultations
         * @description Return one page of the customer's consultations, most recent activity first.
         *
         *     The pinned sort deviation from the admin lists: `-updatedAt`, not
         *     `-createdAt` — a customer looks for the conversation they were just having.
         *     Deleted consultations are absent.
         */
        get: operations["list_chats_api_chats_get"];
        put?: never;
        /**
         * Start a consultation
         * @description Create an empty consultation for the signed-in account and let the advisor open it.
         *
         *     The request body carries an empty attributes object: there is nothing to
         *     supply, the title is derived later from the first user message, and a
         *     consultation is only ever created by an explicit request — never on page
         *     load. The payload is therefore never read — validating it is the point, so
         *     an invented attribute is a 422 instead of a silently ignored key.
         *
         *     The advisor speaks first: a response turn is started immediately, so the
         *     201 already carries `activeOperationId` and the greeting arrives over SSE as
         *     an ordinary assistant message. It does not name the consultation — the title
         *     still comes from the first *user* message.
         */
        post: operations["create_chat_api_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one consultation
         * @description Return one of the customer's own, live consultations.
         */
        get: operations["get_chat_api_chats__chat_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a consultation
         * @description Soft-delete one of the customer's own consultations.
         *
         *     The row and its messages stay in the database behind the ownership check,
         *     which is why a second DELETE answers 404. Nothing is announced over SSE:
         *     only the owner can see this list, and their own mutation invalidates it.
         */
        delete: operations["delete_chat_api_chats__chat_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the source documents of one product
         * @description Return every document of one product, Wikipedia first, then oldest first.
         *
         *     Unpaginated on purpose: ingestion stores a handful of documents per model
         *     (one Wikipedia article plus at most six web sources), and the review screen
         *     needs the complete list to build its document picker.
         */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List product images
         * @description Return the images of one product (or of the whole catalogue), newest first.
         *
         *     Unpaginated on purpose: ingestion stores at most one image per run, so a
         *     product has a handful of rows and the review screen renders the newest.
         */
        get: operations["list_product_images_api_product_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve or reject a product image
         * @description Move one image to a new moderation state.
         *
         *     Legal moves are pinned in `product_service.LEGAL_IMAGE_TRANSITIONS`;
         *     anything else — including a no-op — is a 422 `invalid-transition`.
         */
        patch: operations["update_product_image_api_product_images__image_id__patch"];
        trace?: never;
    };
    "/api/manufacturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List manufacturers
         * @description Return one page of the brand list, alphabetically by name.
         */
        get: operations["list_manufacturers_api_manufacturers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturers/{manufacturer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a manufacturer
         * @description Return one manufacturer.
         */
        get: operations["get_manufacturer_api_manufacturers__manufacturer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturers/{manufacturer_id}/buildinglines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a manufacturer's buildingline values
         * @description Return `manufacturer_id`'s distinct, sorted `buildingline` values.
         *
         *     Backs the identity review form's family `Autocomplete` (ui-spec API-5),
         *     via 6.10's `product_service.list_buildinglines` — read-only, admin-only.
         */
        get: operations["list_buildinglines_api_manufacturers__manufacturer_id__buildinglines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List operations
         * @description Return one page of operations, newest first.
         */
        get: operations["list_operations_api_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products
         * @description Return one page of the catalogue, newest first.
         */
        get: operations["list_products_api_products_get"];
        put?: never;
        /**
         * Add a product to the backlog
         * @description Create an entry from a display name and start ingesting it.
         *
         *     Adding a model auto-starts its ingestion: the row is created in `backlog`,
         *     moved to `ingesting` and its job enqueued — every step committed before the
         *     next — so the answer already carries the state the admin backlog shows.
         */
        post: operations["create_product_api_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a product
         * @description Return one product with both of its specification revisions.
         */
        get: operations["get_product_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a product's identity, draft specification and/or status
         * @description Replace the identity block, the draft specification and/or the status.
         *
         *     All three attributes are optional and applied **in this order — identity,
         *     then draft specification, then status (D2)** — so a request that fills a
         *     missing identity and approves in the same call has the identity already
         *     written when the D4 `IncompleteIdentityError` guard runs; reversing the
         *     order would make that request fail the guard even though it supplies
         *     everything needed. `identity` is a full-object replace through
         *     `product_service.assign_identity`, the block's only writer; the response is
         *     always rendered from the row *after* every requested change, so it carries
         *     the recomputed `slug`. A transition to `ingesting` is a retry: it
         *     re-enqueues the ingestion job server-side, so the UI only ever asks for the
         *     status it wants.
         */
        patch: operations["update_product_api_products__product_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BrowseSort
         * @description The orderings the customer catalogue offers, spelled as they go on the wire.
         *
         *     Members are the wire values (`sort=-msrpEur`), so the route validates against
         *     this enum instead of restating the vocabulary.
         * @enum {string}
         */
        BrowseSort: "name" | "-name" | "msrpEur" | "-msrpEur";
        /**
         * BuildinglinesDocument
         * @description Body of `GET /api/manufacturers/{id}/buildinglines`: `{"data": [...]}`.
         */
        BuildinglinesDocument: {
            /** Data */
            data: string[];
        };
        /**
         * CatalogueImage
         * @description One approved picture: the three variant URLs plus its attribution.
         *
         *     Extends the pinned `ImageVariants` rather than restating the variant names,
         *     so the URL formula stays in one place. `attribution` travels with the URLs
         *     because the gallery must always render it — that is the licence compliance.
         */
        CatalogueImage: {
            /** Thumb */
            thumb: string;
            /** Card */
            card: string;
            /** Detail */
            detail: string;
            /** Attribution */
            attribution: string | null;
        };
        /**
         * CatalogueModelAttributes
         * @description The pinned attribute set of the detail page — self-contained on purpose.
         */
        CatalogueModelAttributes: {
            /** Name */
            name: string;
            /** Manufacturer */
            manufacturer: string | null;
            specs: components["schemas"]["CatalogueModelSpecs"];
            /** Article */
            article: string | null;
            /** Sources */
            sources: components["schemas"]["CatalogueSource"][];
            /** Images */
            images: components["schemas"]["CatalogueImage"][];
            /** Variants */
            variants: components["schemas"]["ProductVariant"][];
        };
        /**
         * CatalogueModelDocument
         * @description Body of `GET /api/catalogue-models/{motorbike_id}`.
         */
        CatalogueModelDocument: {
            data: components["schemas"]["CatalogueModelResource"];
        };
        /**
         * CatalogueModelListDocument
         * @description Body of `GET /api/catalogue-models`.
         */
        CatalogueModelListDocument: {
            /** Data */
            data: components["schemas"]["CatalogueModelSummaryResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * CatalogueModelResource
         * @description A catalogue-model resource object as it appears in the detail document.
         */
        CatalogueModelResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default catalogue-models
             * @constant
             */
            type: "catalogue-models";
            attributes: components["schemas"]["CatalogueModelAttributes"];
        };
        /**
         * CatalogueModelSpecs
         * @description The verified specification of one model: the 13 frozen comparison fields.
         *
         *     Field order mirrors `catalogue_search_service.COMPARISON_SPEC_FIELDS`, and
         *     every field is always present — `null` is the honest answer for a value the
         *     catalogue never verified, and the detail table renders the gap.
         */
        CatalogueModelSpecs: {
            category: components["schemas"]["SpecCategory"] | null;
            /** Enginecc */
            engineCc: number | null;
            /** Cylinders */
            cylinders: number | null;
            /** Powerkw */
            powerKw: number | null;
            /** Torquenm */
            torqueNm: number | null;
            /** Wetweightkg */
            wetWeightKg: number | null;
            /** Seatheightmm */
            seatHeightMm: number | null;
            /** Tankcapacityl */
            tankCapacityL: number | null;
            /** Topspeedkmh */
            topSpeedKmh: number | null;
            /** Abs */
            abs: boolean | null;
            /** A2Eligible */
            a2Eligible: boolean | null;
            priceBand: components["schemas"]["PriceBand"] | null;
            /** Msrpeur */
            msrpEur: number | null;
        };
        /**
         * CatalogueModelSummaryAttributes
         * @description The pinned attribute set of one browse card.
         */
        CatalogueModelSummaryAttributes: {
            /** Name */
            name: string;
            /** Manufacturer */
            manufacturer: string | null;
            category: components["schemas"]["SpecCategory"] | null;
            /** Enginecc */
            engineCc: number | null;
            /** Powerkw */
            powerKw: number | null;
            /** Wetweightkg */
            wetWeightKg: number | null;
            /** Seatheightmm */
            seatHeightMm: number | null;
            /** A2Eligible */
            a2Eligible: boolean | null;
            priceBand: components["schemas"]["PriceBand"] | null;
            /** Msrpeur */
            msrpEur: number | null;
            /** Imageurl */
            imageUrl: string | null;
        };
        /**
         * CatalogueModelSummaryResource
         * @description A catalogue-model resource object as it appears in the list.
         */
        CatalogueModelSummaryResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default catalogue-models
             * @constant
             */
            type: "catalogue-models";
            attributes: components["schemas"]["CatalogueModelSummaryAttributes"];
        };
        /**
         * CatalogueSource
         * @description One provenance entry: what a document is, and where it can be read.
         */
        CatalogueSource: {
            /** Sourcetitle */
            sourceTitle: string;
            /** Sourceurl */
            sourceUrl: string | null;
        };
        /**
         * ChatAttributes
         * @description The pinned attribute set of a consultation.
         */
        ChatAttributes: {
            /** Title */
            title: string | null;
            /** Activeoperationid */
            activeOperationId: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ChatCreateAttributes
         * @description No attributes at all — a consultation is created empty.
         */
        ChatCreateAttributes: Record<string, never>;
        /**
         * ChatCreateRequest
         * @description Body of `POST /api/chats`.
         */
        ChatCreateRequest: {
            data: components["schemas"]["ChatCreateResource"];
        };
        /**
         * ChatCreateResource
         * @description The resource object of a create request.
         */
        ChatCreateResource: {
            /**
             * Type
             * @default chats
             * @constant
             */
            type: "chats";
            attributes: components["schemas"]["ChatCreateAttributes"];
        };
        /**
         * ChatDocument
         * @description Body of `GET`/`POST` on a single consultation.
         */
        ChatDocument: {
            data: components["schemas"]["ChatResource"];
        };
        /**
         * ChatListDocument
         * @description Body of `GET /api/chats`.
         */
        ChatListDocument: {
            /** Data */
            data: components["schemas"]["ChatResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * ChatMessageAttributes
         * @description The pinned attribute set of a message.
         *
         *     The three traces are empty lists on a user message and on an assistant
         *     message that needed no tools.
         */
        ChatMessageAttributes: {
            role: components["schemas"]["ChatMessageRole"];
            /** Body */
            body: string;
            /** Toolcalls */
            toolCalls: components["schemas"]["ToolCall"][];
            /** Sources */
            sources: components["schemas"]["MessageSource"][];
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ChatMessageCreateAttributes
         * @description What a customer may send: which consultation, and what they said.
         */
        ChatMessageCreateAttributes: {
            /**
             * Chatid
             * @description ULID of the consultation this message belongs to.
             */
            chatId: string;
            /**
             * Body
             * @description The customer's message, at most 4000 characters.
             */
            body: string;
        };
        /**
         * ChatMessageCreateRequest
         * @description Body of `POST /api/chat-messages`.
         */
        ChatMessageCreateRequest: {
            data: components["schemas"]["ChatMessageCreateResource"];
        };
        /**
         * ChatMessageCreateResource
         * @description The resource object of a create request.
         */
        ChatMessageCreateResource: {
            /**
             * Type
             * @default chat-messages
             * @constant
             */
            type: "chat-messages";
            attributes: components["schemas"]["ChatMessageCreateAttributes"];
        };
        /**
         * ChatMessageDocument
         * @description Body of `POST /api/chat-messages`.
         */
        ChatMessageDocument: {
            data: components["schemas"]["ChatMessageResource"];
        };
        /**
         * ChatMessageListDocument
         * @description Body of `GET /api/chat-messages`.
         */
        ChatMessageListDocument: {
            /** Data */
            data: components["schemas"]["ChatMessageResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * ChatMessageResource
         * @description A message resource object.
         */
        ChatMessageResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default chat-messages
             * @constant
             */
            type: "chat-messages";
            attributes: components["schemas"]["ChatMessageAttributes"];
        };
        /**
         * ChatMessageRole
         * @description Who wrote a message.
         *
         *     Only these two: the system prompt is code and never a row, and tool traffic
         *     lives in the JSONB columns of the assistant message it belongs to.
         * @enum {string}
         */
        ChatMessageRole: "user" | "assistant";
        /**
         * ChatResource
         * @description A consultation resource object.
         */
        ChatResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default chats
             * @constant
             */
            type: "chats";
            attributes: components["schemas"]["ChatAttributes"];
        };
        /**
         * DocumentAttributes
         * @description The pinned attribute set of a source document.
         */
        DocumentAttributes: {
            sourceType: components["schemas"]["SourceType"];
            /** Sourceurl */
            sourceUrl: string | null;
            /** Sourcetitle */
            sourceTitle: string;
            /** Contentmarkdown */
            contentMarkdown: string;
            /**
             * Fetchedat
             * Format: date-time
             */
            fetchedAt: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * DocumentListDocument
         * @description Body of `GET /api/documents`.
         */
        DocumentListDocument: {
            /** Data */
            data: components["schemas"]["DocumentResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * DocumentResource
         * @description A source-document resource object.
         */
        DocumentResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default documents
             * @constant
             */
            type: "documents";
            attributes: components["schemas"]["DocumentAttributes"];
        };
        /**
         * DraftSpecRequest
         * @description A full draft specification: every omitted field is reset.
         *
         *     Full-object replace is the pinned semantics — the SPA merges the last
         *     fetched `draftSpec` with its form values before sending, so fields the form
         *     does not show survive a save.
         */
        DraftSpecRequest: {
            category?: components["schemas"]["SpecCategory"] | null;
            /** Enginecc */
            engineCc?: number | null;
            /** Cylinders */
            cylinders?: number | null;
            /** Powerkw */
            powerKw?: number | null;
            /** Torquenm */
            torqueNm?: number | null;
            /** Wetweightkg */
            wetWeightKg?: number | null;
            /** Seatheightmm */
            seatHeightMm?: number | null;
            /** Tankcapacityl */
            tankCapacityL?: number | null;
            /** Topspeedkmh */
            topSpeedKmh?: number | null;
            /** Abs */
            abs?: boolean | null;
            /** A2Eligible */
            a2Eligible?: boolean | null;
            priceBand?: components["schemas"]["PriceBand"] | null;
            /** Msrpeur */
            msrpEur?: number | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
            /** Sourcehints */
            sourceHints?: {
                [key: string]: unknown;
            } | null;
            /** Extractedat */
            extractedAt?: string | null;
        };
        /**
         * ErrorDocument
         * @description The body of every failed request this layer produces.
         */
        ErrorDocument: {
            /** Errors */
            errors: components["schemas"]["ErrorObject"][];
        };
        /**
         * ErrorObject
         * @description One JSON:API error object.
         *
         *     `status` is the HTTP status as a string (JSON:API requires that), `code` is
         *     the stable application code the frontend branches on, `detail` is an English
         *     sentence for developers and log lines — never parsed.
         */
        ErrorObject: {
            /** Status */
            status: string;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload: the process is up and serving requests.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * IdentityRequest
         * @description The writable identity block: a full-object replace (D2), never a merge.
         *
         *     Boundary caps reuse 6.10's `identity_validation` module rather than
         *     restating its regex/caps: `variants` entries are validated by its
         *     `Variant` model (name length, description length — `slug` is never
         *     trusted from input, `identity_validation.Variant` always recomputes it),
         *     and `type_codes`/`variants` are capped at
         *     `identity_validation.MAX_TYPE_CODES`/`MAX_VARIANTS`. The year bounds
         *     (`IDENTITY_YEAR_MIN` through the current year plus two) and the
         *     `yearTo >= yearFrom` pair check are this schema's own — `assign_identity`
         *     itself does not check plausibility, only shape.
         *
         *     An entry `assign_identity`'s own `identity_validation` pass would drop
         *     (an unknown `specs` key, a duplicate slug, a type code past the cap) is
         *     still accepted **here** and silently dropped there with a `logger.warning`
         *     — this schema's checks are a stricter, earlier subset for immediate
         *     feedback, not a second implementation of the same rules.
         */
        IdentityRequest: {
            /** Manufacturerid */
            manufacturerId?: string | null;
            /** Buildingline */
            buildingline?: string | null;
            /** Modelname */
            modelName?: string | null;
            /** Yearfrom */
            yearFrom?: number | null;
            /** Yearto */
            yearTo?: number | null;
            /**
             * Typecodes
             * @default []
             */
            typeCodes: string[];
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["Variant"][];
        };
        /**
         * ImageStatus
         * @description Moderation state of an image.
         * @enum {string}
         */
        ImageStatus: "pending" | "approved" | "rejected";
        /**
         * ImageVariants
         * @description The three resized renditions of one image, as URLs.
         *
         *     The field names *are* the variant names of the path formula, which is why
         *     they are spelled out rather than kept in a separate constant.
         */
        ImageVariants: {
            /** Thumb */
            thumb: string;
            /** Card */
            card: string;
            /** Detail */
            detail: string;
        };
        /**
         * LoginRequest
         * @description Credentials for an existing account, plus the cookie lifetime choice.
         *
         *     Deliberately unvalidated beyond the username normalisation and the
         *     password length ceiling: a credential that could not possibly match is
         *     rejected by `user_service.authenticate` with a 401, on the same
         *     constant-time path as any other wrong password. `password`'s
         *     `max_length` is the one sanctioned exception (OQ-A) — it exists solely to
         *     cap Argon2 work per attempt, not as data-entry validation.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Rememberme
             * @default false
             */
            rememberMe: boolean;
        };
        /**
         * ManufacturerAttributes
         * @description The pinned attribute set of a manufacturer.
         */
        ManufacturerAttributes: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string | null;
            /** Logopath */
            logoPath: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ManufacturerDocument
         * @description Body of `GET /api/manufacturers/{id}`.
         */
        ManufacturerDocument: {
            data: components["schemas"]["ManufacturerResource"];
        };
        /**
         * ManufacturerListDocument
         * @description Body of `GET /api/manufacturers`.
         */
        ManufacturerListDocument: {
            /** Data */
            data: components["schemas"]["ManufacturerResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * ManufacturerResource
         * @description A manufacturer resource object.
         */
        ManufacturerResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default manufacturers
             * @constant
             */
            type: "manufacturers";
            attributes: components["schemas"]["ManufacturerAttributes"];
        };
        /**
         * MessageSource
         * @description One knowledge-base chunk backing this answer.
         *
         *     Provenance, not prose: the UI shows title, heading path and a link, and the
         *     `chunkId` is what ties a claim back to the ingested document it came from.
         */
        MessageSource: {
            /** Chunkid */
            chunkId: string;
            /** Motorbikeid */
            motorbikeId: string;
            /** Sourcedocumentid */
            sourceDocumentId: string;
            /** Sourceurl */
            sourceUrl: string | null;
            /** Sourcetitle */
            sourceTitle: string;
            /** Headingpath */
            headingPath: string | null;
            /** Score */
            score: number;
        };
        /**
         * Meta
         * @description Top-level `meta` of a collection document.
         */
        Meta: {
            /** Totalcount */
            totalCount: number;
        };
        /**
         * MotorbikeStatus
         * @description Position of a catalogue entry in the curation workflow.
         *
         *     Legal transitions are enforced by `app.services.product_service.transition`;
         *     `rejected` is deliberately **not** terminal (an admin re-queues ingestion).
         * @enum {string}
         */
        MotorbikeStatus: "backlog" | "ingesting" | "in_review" | "approved" | "rejected";
        /**
         * OperationAttributes
         * @description The pinned attribute set of an operation.
         */
        OperationAttributes: {
            /** Type */
            type: string;
            status: components["schemas"]["OperationStatus"];
            /** Progress */
            progress: number;
            /** Message */
            message: string | null;
            /** Error */
            error: string | null;
            /** Entitytype */
            entityType: string | null;
            /** Entityid */
            entityId: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Startedat */
            startedAt: string | null;
            /** Finishedat */
            finishedAt: string | null;
        };
        /**
         * OperationListDocument
         * @description Body of `GET /api/operations`.
         */
        OperationListDocument: {
            /** Data */
            data: components["schemas"]["OperationResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * OperationResource
         * @description An operation resource object.
         */
        OperationResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default operations
             * @constant
             */
            type: "operations";
            attributes: components["schemas"]["OperationAttributes"];
        };
        /**
         * OperationStatus
         * @description Lifecycle position of an operation.
         *
         *     `queued` → `running` → `succeeded` | `failed`; the terminal states are
         *     final. Progress and message are advisory, the status is authoritative.
         * @enum {string}
         */
        OperationStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * PriceBand
         * @enum {string}
         */
        PriceBand: "budget" | "mid" | "upper" | "premium";
        /**
         * ProductAttributes
         * @description The pinned attribute set of a product.
         *
         *     `buildingline` and `suggestion` carry an explicit `None` default even
         *     though nothing here ever *omits* them (`endpoints/products.py::_resource`
         *     always supplies a value): FastAPI's exported OpenAPI schema drops the
         *     `default` key for a field whose default is `None` and whose type already
         *     allows `null`, which keeps those two out of the `required` list and, in
         *     turn, keeps the generated TypeScript member optional (`?:`) rather than
         *     mandatory — so a `Product`-typed fixture written before this step (there
         *     are several, across the frontend) stays structurally valid without an
         *     edit. The other three additions (`queryName`, `typeCodes`, `variants`)
         *     cannot take the same shortcut honestly: they are never actually absent or
         *     `null` on a real row, so giving them a non-`None` default would still
         *     leave them required in the generated type (FastAPI keeps a non-`None`
         *     default in the schema, and `openapi-typescript`'s `defaultNonNullable`
         *     forces a defaulted-but-present field back to required) while also
         *     misstating what the wire actually sends. They stay required, matching
         *     every other non-nullable field this model already has.
         */
        ProductAttributes: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Queryname */
            queryName: string;
            /** Manufacturer */
            manufacturer: string | null;
            /** Buildingline */
            buildingline?: string | null;
            /** Modelname */
            modelName: string | null;
            /** Yearfrom */
            yearFrom: number | null;
            /** Yearto */
            yearTo: number | null;
            /** Typecodes */
            typeCodes: string[];
            /** Variants */
            variants: components["schemas"]["ProductVariant"][];
            suggestion?: components["schemas"]["ProductSuggestion"] | null;
            status: components["schemas"]["MotorbikeStatus"];
            draftSpec: components["schemas"]["SpecAttributes"] | null;
            verifiedSpec: components["schemas"]["SpecAttributes"] | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ProductCreateAttributes
         * @description The single attribute a new catalogue entry is created from.
         */
        ProductCreateAttributes: {
            /**
             * Name
             * @description Display name as entered, e.g. "Suzuki GSR 600".
             */
            name: string;
        };
        /**
         * ProductCreateRequest
         * @description Body of `POST /api/products`.
         */
        ProductCreateRequest: {
            data: components["schemas"]["ProductCreateResource"];
        };
        /**
         * ProductCreateResource
         * @description The resource object of a create request.
         */
        ProductCreateResource: {
            /**
             * Type
             * @default products
             * @constant
             */
            type: "products";
            attributes: components["schemas"]["ProductCreateAttributes"];
        };
        /**
         * ProductDocument
         * @description Body of `GET`/`POST`/`PATCH` on a single product.
         */
        ProductDocument: {
            data: components["schemas"]["ProductResource"];
        };
        /**
         * ProductImageAttributes
         * @description The pinned attribute set of a product image.
         */
        ProductImageAttributes: {
            /** Sourceurl */
            sourceUrl: string;
            /** Attribution */
            attribution: string | null;
            status: components["schemas"]["ImageStatus"];
            variants: components["schemas"]["ImageVariants"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ProductImageDocument
         * @description Body of `PATCH` on a single product image.
         */
        ProductImageDocument: {
            data: components["schemas"]["ProductImageResource"];
        };
        /**
         * ProductImageListDocument
         * @description Body of `GET /api/product-images`.
         */
        ProductImageListDocument: {
            /** Data */
            data: components["schemas"]["ProductImageResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * ProductImagePatchAttributes
         * @description The one writable attribute of an image: its moderation state.
         */
        ProductImagePatchAttributes: {
            status: components["schemas"]["ImageStatus"];
        };
        /**
         * ProductImagePatchRequest
         * @description Body of `PATCH /api/product-images/{id}`.
         */
        ProductImagePatchRequest: {
            data: components["schemas"]["ProductImagePatchResource"];
        };
        /**
         * ProductImagePatchResource
         * @description The resource object of an image update request.
         */
        ProductImagePatchResource: {
            /**
             * Type
             * @default product-images
             * @constant
             */
            type: "product-images";
            attributes: components["schemas"]["ProductImagePatchAttributes"];
        };
        /**
         * ProductImageResource
         * @description A product-image resource object.
         */
        ProductImageResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default product-images
             * @constant
             */
            type: "product-images";
            attributes: components["schemas"]["ProductImageAttributes"];
        };
        /**
         * ProductListDocument
         * @description Body of `GET /api/products`.
         */
        ProductListDocument: {
            /** Data */
            data: components["schemas"]["ProductResource"][];
            meta: components["schemas"]["Meta"];
        };
        /**
         * ProductPatchAttributes
         * @description The writable attributes of an existing product.
         *
         *     All three are optional; `verifiedSpec` (and anything else) is rejected
         *     outright. Applied by the endpoint in a fixed order — identity, then draft
         *     specification, then status (D2) — documented on `update_product` itself.
         */
        ProductPatchAttributes: {
            /** @description Target status; must be legal for the current one. */
            status?: components["schemas"]["MotorbikeStatus"] | null;
            /** @description Full replacement of the draft specification. */
            draftSpec?: components["schemas"]["DraftSpecRequest"] | null;
            /** @description Full replacement of the identity block (D2). */
            identity?: components["schemas"]["IdentityRequest"] | null;
        };
        /**
         * ProductPatchRequest
         * @description Body of `PATCH /api/products/{id}`.
         */
        ProductPatchRequest: {
            data: components["schemas"]["ProductPatchResource"];
        };
        /**
         * ProductPatchResource
         * @description The resource object of an update request.
         */
        ProductPatchResource: {
            /**
             * Type
             * @default products
             * @constant
             */
            type: "products";
            attributes: components["schemas"]["ProductPatchAttributes"];
        };
        /**
         * ProductResource
         * @description A product resource object.
         */
        ProductResource: {
            /** Id */
            id: string;
            /**
             * Type
             * @default products
             * @constant
             */
            type: "products";
            attributes: components["schemas"]["ProductAttributes"];
        };
        /**
         * ProductSuggestion
         * @description The unverified claim `motorbikes.suggestion` carries, camelCased (D6).
         *
         *     Never written by any schema in this module — only a human "using the
         *     claim" in the review form copies a value into the typed `identity` block,
         *     and that goes through `IdentityRequest` like any other admin edit. Unknown
         *     keys are ignored, never rejected: this projects a stored JSON document,
         *     not a request body.
         */
        ProductSuggestion: {
            /** Source */
            source: string;
            /** Raw */
            raw: string;
            /** Manufacturer */
            manufacturer: string | null;
            /** Model */
            model: string | null;
            /** Yearfrom */
            yearFrom: number | null;
            /** Yearto */
            yearTo: number | null;
            /** Inproduction */
            inProduction: boolean;
            /** Yearranges */
            yearRanges: components["schemas"]["SuggestionYearRange"][];
            /** Typecodes */
            typeCodes: string[];
            /** Links */
            links: string[];
        };
        /**
         * ProductVariant
         * @description One trim, as returned: a spec delta plus free text (D1/D2, §2.5).
         *
         *     `specs` keys stay the snake_case frozen spec column names verbatim — they
         *     are data stored in the row's JSONB, not schema fields, so they are never
         *     camelCased.
         */
        ProductVariant: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Specs */
            specs: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ReadinessResponse
         * @description Readiness payload: state of the dependencies the app cannot work without.
         *
         *     Redis is intentionally absent — a broker outage delays background jobs but
         *     must not take the HTTP application out of rotation.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
        };
        /**
         * Recommendation
         * @description One recommended model, snapshotted when the answer was written.
         *
         *     A write-time snapshot rather than a catalogue reference: plain users cannot
         *     read `/api/products` in this phase, so the card has to be self-contained.
         *     Staleness is accepted.
         */
        Recommendation: {
            /** Motorbikeid */
            motorbikeId: string;
            /** Name */
            name: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Rationale */
            rationale: string;
            /** Matchedpreferences */
            matchedPreferences: string[];
            keySpecs: components["schemas"]["RecommendationKeySpecs"];
        };
        /**
         * RecommendationKeySpecs
         * @description The specification snippet a recommendation card shows.
         *
         *     Every field is nullable: a missing verified specification stays missing —
         *     the advisor never guesses a number.
         */
        RecommendationKeySpecs: {
            category: components["schemas"]["SpecCategory"] | null;
            /** Enginecc */
            engineCc: number | null;
            /** Powerkw */
            powerKw: number | null;
            /** Wetweightkg */
            wetWeightKg: number | null;
            /** Seatheightmm */
            seatHeightMm: number | null;
            priceBand: components["schemas"]["PriceBand"] | null;
        };
        /**
         * RegisterRequest
         * @description Credentials for a new account, carrying the pinned validation rules.
         */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * SourceType
         * @description Where a document came from; also drives list ordering and prompts.
         * @enum {string}
         */
        SourceType: "wikipedia" | "product" | "technical" | "magazine" | "upload" | "listing";
        /**
         * SpecAttributes
         * @description One specification revision of a product, as returned.
         */
        SpecAttributes: {
            category: components["schemas"]["SpecCategory"] | null;
            /** Enginecc */
            engineCc: number | null;
            /** Cylinders */
            cylinders: number | null;
            /** Powerkw */
            powerKw: number | null;
            /** Torquenm */
            torqueNm: number | null;
            /** Wetweightkg */
            wetWeightKg: number | null;
            /** Seatheightmm */
            seatHeightMm: number | null;
            /** Tankcapacityl */
            tankCapacityL: number | null;
            /** Topspeedkmh */
            topSpeedKmh: number | null;
            /** Abs */
            abs: boolean | null;
            /** A2Eligible */
            a2Eligible: boolean | null;
            priceBand: components["schemas"]["PriceBand"] | null;
            /** Msrpeur */
            msrpEur: number | null;
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
            /** Sourcehints */
            sourceHints: {
                [key: string]: unknown;
            } | null;
            /** Extractedat */
            extractedAt: string | null;
        };
        /**
         * SpecCategory
         * @enum {string}
         */
        SpecCategory: "naked" | "sport" | "sport_touring" | "touring" | "adventure" | "cruiser" | "classic" | "scrambler" | "enduro" | "supermoto" | "scooter";
        /**
         * SuggestionYearRange
         * @description One `(from, to)` pair out of a suggestion's claimed year ranges.
         *
         *     `from` is a Python keyword, hence the `from_` field name with an explicit
         *     alias — the one place in this module the alias generator's default
         *     (`to_camel("from_") == "from_"`, verified: it does not strip a trailing
         *     underscore) would get it wrong.
         */
        SuggestionYearRange: {
            /** From */
            from?: number | null;
            /** To */
            to?: number | null;
        };
        /**
         * ToolCall
         * @description One tool the advisor executed for this turn, with its outcome.
         *
         *     Every executed call is recorded — the retrieval and comparison tools graders
         *     look for, and the write tools (`record_preference`, `flag_unknown_bike`,
         *     `present_recommendations`) alike.
         */
        ToolCall: {
            /** Id */
            id: string;
            /** Tool */
            tool: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ToolCallStatus"];
            /** Error */
            error: string | null;
        };
        /**
         * ToolCallStatus
         * @description How an executed tool call ended.
         * @enum {string}
         */
        ToolCallStatus: "succeeded" | "failed";
        /**
         * UserResponse
         * @description The authenticated account, as every `/auth/*` success body returns it.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Variant
         * @description One trim: a spec delta plus free text — never the base (§2.5).
         *
         *     `slug` is always recomputed from `name` via `product_service.slugify` and
         *     never trusted from input, so it needs no caller-supplied value. `specs`
         *     keys are **not** restricted here — `normalize_variants` drops any key
         *     outside `VARIANT_SPEC_KEYS` after validation, keeping the entry (a key is
         *     dropped, not the variant).
         */
        Variant: {
            /**
             * Slug
             * @default
             */
            slug: string;
            /** Name */
            name: string;
            /**
             * Specs
             * @default {}
             */
            specs: {
                [key: string]: unknown;
            };
            /**
             * Description
             * @default
             */
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream of `operation.updated`, `product.updated` and `document.updated` notifications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    list_catalogue_models_api_catalogue_models_get: {
        parameters: {
            query?: {
                /** @description Comma-separated list of categories: naked, sport, sport_touring, touring, adventure, cruiser, classic, scrambler, enduro, supermoto, scooter */
                "filter[category]"?: string | null;
                /** @description Comma-separated list of price bands: budget, mid, upper, premium */
                "filter[priceBand]"?: string | null;
                /** @description Comma-separated list of manufacturer ULIDs; an unknown id matches nothing. */
                "filter[manufacturer]"?: string | null;
                /** @description Smallest displacement in cm³. */
                "filter[engineCcMin]"?: number | null;
                /** @description Largest displacement in cm³. */
                "filter[engineCcMax]"?: number | null;
                /** @description Smallest maximum power in kW. */
                "filter[powerKwMin]"?: number | null;
                /** @description Largest maximum power in kW. */
                "filter[powerKwMax]"?: number | null;
                /** @description Heaviest wet weight in kg. */
                "filter[wetWeightKgMax]"?: number | null;
                /** @description Highest seat height in mm. */
                "filter[seatHeightMmMax]"?: number | null;
                /** @description Restrict to A2-eligible models. */
                "filter[a2Eligible]"?: boolean | null;
                /** @description Ordering; price sorts put models without a price last. */
                sort?: components["schemas"]["BrowseSort"];
                /** @description 1-based page number (maximum 10000). */
                "page[number]"?: number;
                /** @description Rows per page (maximum 100). */
                "page[size]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueModelListDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalogue_model_api_catalogue_models__motorbike_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the catalogue model. */
                motorbike_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueModelDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_messages_api_chat_messages_get: {
        parameters: {
            query?: {
                /** @description ULID of the consultation whose messages to return (required). */
                "filter[chat]"?: string | null;
                /** @description 1-based page number (maximum 10000). */
                "page[number]"?: number;
                /** @description Rows per page (maximum 100). */
                "page[size]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageListDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_message_api_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_chats_get: {
        parameters: {
            query?: {
                /** @description 1-based page number (maximum 10000). */
                "page[number]"?: number;
                /** @description Rows per page (maximum 100). */
                "page[size]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatListDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_api_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_api_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the consultation. */
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_api_chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the consultation. */
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: {
                /** @description ULID of the product whose documents to return (required). */
                "filter[product]"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_images_api_product_images_get: {
        parameters: {
            query?: {
                /** @description ULID of the product whose images to return. */
                "filter[product]"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageListDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_image_api_product_images__image_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the image. */
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductImagePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
        };
    };
    list_manufacturers_api_manufacturers_get: {
        parameters: {
            query?: {
                /** @description 1-based page number (maximum 10000). */
                "page[number]"?: number;
                /** @description Rows per page (maximum 100). */
                "page[size]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturerListDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manufacturer_api_manufacturers__manufacturer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the manufacturer. */
                manufacturer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturerDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_buildinglines_api_manufacturers__manufacturer_id__buildinglines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the manufacturer. */
                manufacturer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildinglinesDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operations_api_operations_get: {
        parameters: {
            query?: {
                /** @description Comma-separated list of entity types, e.g. `motorbike`. */
                "filter[entityType]"?: string | null;
                /** @description Comma-separated list of entity ids. */
                "filter[entityId]"?: string | null;
                /** @description Comma-separated list of statuses: queued, running, succeeded, failed */
                "filter[status]"?: string | null;
                /** @description 1-based page number (maximum 10000). */
                "page[number]"?: number;
                /** @description Rows per page (maximum 100). */
                "page[size]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationListDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                /** @description Comma-separated list of statuses: backlog, ingesting, in_review, approved, rejected */
                "filter[status]"?: string | null;
                /** @description 1-based page number (maximum 10000). */
                "page[number]"?: number;
                /** @description Rows per page (maximum 100). */
                "page[size]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDocument"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the product. */
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ULID of the product. */
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDocument"];
                };
            };
        };
    };
}
