"""add chat tables

The three tables of a consultation: `chats` plus the two that hang off it
(`chat_messages`, `chat_preferences`). The only Phase-3 migration.

Autogenerated, then hand-reviewed: the `id` columns were moved to the front
(autogenerate appends mixin columns), and the downgrade drops the two new enum
types explicitly — `create_table` creates them implicitly but `drop_table`
leaves them behind, which makes re-applying this revision fail with
"type ... already exists" (same reason as `4ea01933a43b`).

Note `chats.active_operation_id` deliberately carries **no** foreign key: it
mirrors the loose entity coupling of `operations`.

Revision ID: fb2747f937c4
Revises: 485b2042d7f8
Create Date: 2026-08-27 10:35:36.707895

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb2747f937c4"
down_revision: str | Sequence[str] | None = "485b2042d7f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CHAT_MESSAGE_ROLE_ENUM_NAME = "chat_message_role"
PREFERENCE_FIRMNESS_ENUM_NAME = "preference_firmness"


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "chats",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("active_operation_id", sa.String(length=26), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_chats_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
    )
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("chat_id", sa.String(length=26), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name=CHAT_MESSAGE_ROLE_ENUM_NAME),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "tool_calls",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "recommendations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_chat_messages_chat_id_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(op.f("ix_chat_messages_chat_id"), "chat_messages", ["chat_id"], unique=False)
    op.create_table(
        "chat_preferences",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("chat_id", sa.String(length=26), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column(
            "firmness",
            sa.Enum("hard", "soft", "exploring", name=PREFERENCE_FIRMNESS_ENUM_NAME),
            nullable=False,
        ),
        sa.Column("superseded_by_id", sa.String(length=26), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_chat_preferences_chat_id_chats"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["chat_preferences.id"],
            name=op.f("fk_chat_preferences_superseded_by_id_chat_preferences"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_preferences")),
    )
    op.create_index(
        op.f("ix_chat_preferences_chat_id"), "chat_preferences", ["chat_id"], unique=False
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_index(op.f("ix_chat_preferences_chat_id"), table_name="chat_preferences")
    op.drop_table("chat_preferences")
    op.drop_index(op.f("ix_chat_messages_chat_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chats_user_id"), table_name="chats")
    op.drop_table("chats")
    # Hand-added: the enum types outlive the tables that created them.
    bind = op.get_bind()
    for enum_name in (PREFERENCE_FIRMNESS_ENUM_NAME, CHAT_MESSAGE_ROLE_ENUM_NAME):
        sa.Enum(name=enum_name).drop(bind)
