"""add catalogue tables

The four tables of the curation workflow: `motorbikes` plus the three that hang
off it (`source_documents`, `motorbike_specs`, `motorbike_images`).

Autogenerated, then hand-reviewed: the `id` columns were moved to the front
(autogenerate appends mixin columns), and the downgrade drops the four enum
types explicitly — `create_table` creates them implicitly but `drop_table`
leaves them behind, which makes re-applying this revision fail with
"type ... already exists".

Revision ID: 4ea01933a43b
Revises: f68e3fe43b2d
Create Date: 2026-08-26 19:41:33.885912

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ea01933a43b"
down_revision: str | Sequence[str] | None = "f68e3fe43b2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MOTORBIKE_STATUS_ENUM_NAME = "motorbike_status"
SOURCE_TYPE_ENUM_NAME = "source_type"
SPEC_KIND_ENUM_NAME = "spec_kind"
IMAGE_STATUS_ENUM_NAME = "image_status"


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "motorbikes",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("manufacturer", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("year_from", sa.SmallInteger(), nullable=True),
        sa.Column("year_to", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "backlog",
                "ingesting",
                "in_review",
                "approved",
                "rejected",
                name=MOTORBIKE_STATUS_ENUM_NAME,
            ),
            server_default="backlog",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_motorbikes")),
        sa.UniqueConstraint("slug", name=op.f("uq_motorbikes_slug")),
    )
    op.create_index(op.f("ix_motorbikes_status"), "motorbikes", ["status"], unique=False)
    op.create_table(
        "source_documents",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("motorbike_id", sa.String(length=26), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "wikipedia",
                "product",
                "technical",
                "magazine",
                "upload",
                name=SOURCE_TYPE_ENUM_NAME,
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("source_title", sa.String(length=512), nullable=False),
        sa.Column("raw_path", sa.String(length=512), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["motorbike_id"],
            ["motorbikes.id"],
            name=op.f("fk_source_documents_motorbike_id_motorbikes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
    )
    op.create_index(
        op.f("ix_source_documents_motorbike_id"), "source_documents", ["motorbike_id"], unique=False
    )
    op.create_table(
        "motorbike_specs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("motorbike_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.Enum("draft", "verified", name=SPEC_KIND_ENUM_NAME), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("engine_cc", sa.Integer(), nullable=True),
        sa.Column("cylinders", sa.SmallInteger(), nullable=True),
        sa.Column("power_kw", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("torque_nm", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("wet_weight_kg", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("seat_height_mm", sa.SmallInteger(), nullable=True),
        sa.Column("tank_capacity_l", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("top_speed_kmh", sa.SmallInteger(), nullable=True),
        sa.Column("abs", sa.Boolean(), nullable=True),
        sa.Column("a2_eligible", sa.Boolean(), nullable=True),
        sa.Column("price_band", sa.String(length=16), nullable=True),
        sa.Column("msrp_eur", sa.Integer(), nullable=True),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_hints", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["motorbike_id"],
            ["motorbikes.id"],
            name=op.f("fk_motorbike_specs_motorbike_id_motorbikes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_motorbike_specs")),
        sa.UniqueConstraint(
            "motorbike_id", "kind", name=op.f("uq_motorbike_specs_motorbike_id_kind")
        ),
    )
    op.create_table(
        "motorbike_images",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("motorbike_id", sa.String(length=26), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name=IMAGE_STATUS_ENUM_NAME),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("original_path", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["motorbike_id"],
            ["motorbikes.id"],
            name=op.f("fk_motorbike_images_motorbike_id_motorbikes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_motorbike_images")),
    )
    op.create_index(
        op.f("ix_motorbike_images_motorbike_id"), "motorbike_images", ["motorbike_id"], unique=False
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_index(op.f("ix_motorbike_images_motorbike_id"), table_name="motorbike_images")
    op.drop_table("motorbike_images")
    op.drop_table("motorbike_specs")
    op.drop_index(op.f("ix_source_documents_motorbike_id"), table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_index(op.f("ix_motorbikes_status"), table_name="motorbikes")
    op.drop_table("motorbikes")
    # Hand-added: the enum types outlive the tables that created them.
    bind = op.get_bind()
    for enum_name in (
        IMAGE_STATUS_ENUM_NAME,
        SPEC_KIND_ENUM_NAME,
        SOURCE_TYPE_ENUM_NAME,
        MOTORBIKE_STATUS_ENUM_NAME,
    ):
        sa.Enum(name=enum_name).drop(bind)
