"""add chunks table

The retrieval unit: slices of `source_documents` with their provenance, the
nullable embedding column and the two retrieval indexes (lexical GIN over a
generated `tsvector`, approximate-nearest-neighbour HNSW over the vector).

Autogenerated, then hand-reviewed like `4ea01933a43b` and `a35f16edce83`: the
`id` column was moved to the front (autogenerate appends mixin columns) and the
`pgvector` type is imported by name instead of being referenced through a
module path autogenerate does not import. No enum type is created here, so the
downgrade needs no explicit `DROP TYPE`.

The `vector(1536)` width is pinned: it must match the configured
`EMBEDDING_DIMENSIONS`, and changing either requires a new revision that alters
this column (and rebuilds `ix_chunks_embedding`).

Revision ID: 0a65339a924a
Revises: a35f16edce83
Create Date: 2026-08-26 22:01:12.057282

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a65339a924a"
down_revision: str | Sequence[str] | None = "a35f16edce83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIMENSIONS = 1536

# HNSW build parameters, pinned in the schema contract.
HNSW_OPTIONS = {"m": 16, "ef_construction": 64}


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "chunks",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("source_document_id", sa.String(length=26), nullable=False),
        sa.Column("motorbike_id", sa.String(length=26), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("heading_path", sa.String(length=512), nullable=True),
        sa.Column("page_number", sa.SmallInteger(), nullable=True),
        sa.Column("embedding", Vector(dim=EMBEDDING_DIMENSIONS), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=True),
        sa.Column(
            "text_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_chunks_source_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "source_document_id", "sequence", name=op.f("uq_chunks_source_document_id_sequence")
        ),
    )
    op.create_index(
        op.f("ix_chunks_embedding"),
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with=HNSW_OPTIONS,
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_chunks_motorbike_id"), "chunks", ["motorbike_id"], unique=False)
    op.create_index(
        op.f("ix_chunks_source_document_id"), "chunks", ["source_document_id"], unique=False
    )
    op.create_index(
        op.f("ix_chunks_text_tsv"), "chunks", ["text_tsv"], unique=False, postgresql_using="gin"
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_index(op.f("ix_chunks_text_tsv"), table_name="chunks", postgresql_using="gin")
    op.drop_index(op.f("ix_chunks_source_document_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_motorbike_id"), table_name="chunks")
    op.drop_index(
        op.f("ix_chunks_embedding"),
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_with=HNSW_OPTIONS,
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chunks")
