"""add manufacturers table

Manufacturers become a first-class table: `motorbikes.manufacturer` (free text)
is replaced by `motorbikes.manufacturer_id` pointing at a `manufacturers` row.
The products API keeps its wire shape by deriving the name from that row.

Hand-written rather than autogenerated, because the order matters: the table and
the foreign key must exist before the legacy strings can be moved into them, and
the legacy column may only be dropped afterwards.

The downgrade restores the legacy column from the related rows, so the
round-trip is lossless up to whitespace collapsing and the casing of the
first-seen spelling (the backfill's own normalisation). No enum type is created
here, so no `DROP TYPE` is needed.

Two deliberate inlinings — a migration must keep working when the application
code moves on: ULIDs are generated here rather than by the ORM default, and the
slug rule is the pinned regex, copied instead of imported from
`app.services.product_service`.

Revision ID: 485b2042d7f8
Revises: 0a65339a924a
Create Date: 2026-08-27 09:42:36.028386

"""

import re
from collections.abc import Sequence
from dataclasses import dataclass, field

import sqlalchemy as sa
from ulid import ULID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "485b2042d7f8"
down_revision: str | Sequence[str] | None = "0a65339a924a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ULID_LENGTH = 26
NAME_LENGTH = 64
SLUG_LENGTH = 64
LOGO_PATH_LENGTH = 512

# The pinned slug rule, inlined (see the module docstring).
_NON_SLUG_CHARACTERS = re.compile(r"[^a-z0-9]+")

# Minimal table definitions for the data migration; the DDL above is the schema.
_manufacturers = sa.table(
    "manufacturers",
    sa.column("id", sa.String),
    sa.column("name", sa.String),
    sa.column("slug", sa.String),
)
_motorbikes = sa.table(
    "motorbikes",
    sa.column("id", sa.String),
    sa.column("manufacturer", sa.String),
    sa.column("manufacturer_id", sa.String),
)


@dataclass
class _Brand:
    """One manufacturer row to insert, plus the rows that will point at it."""

    id: str
    name: str
    slug: str
    motorbike_ids: list[str] = field(default_factory=list)


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "manufacturers",
        sa.Column("id", sa.String(length=ULID_LENGTH), nullable=False),
        sa.Column("name", sa.String(length=NAME_LENGTH), nullable=False),
        sa.Column("slug", sa.String(length=SLUG_LENGTH), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_path", sa.String(length=LOGO_PATH_LENGTH), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturers")),
        sa.UniqueConstraint("slug", name=op.f("uq_manufacturers_slug")),
    )
    op.add_column(
        "motorbikes", sa.Column("manufacturer_id", sa.String(length=ULID_LENGTH), nullable=True)
    )
    op.create_index(
        op.f("ix_motorbikes_manufacturer_id"), "motorbikes", ["manufacturer_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_motorbikes_manufacturer_id_manufacturers"),
        "motorbikes",
        "manufacturers",
        ["manufacturer_id"],
        ["id"],
    )
    _backfill_manufacturers()
    op.drop_column("motorbikes", "manufacturer")


def downgrade() -> None:
    """Revert this revision."""
    op.add_column("motorbikes", sa.Column("manufacturer", sa.String(length=NAME_LENGTH)))
    # Put the brand names back where they came from, then take the table away.
    op.execute(
        _motorbikes.update()
        .where(_motorbikes.c.manufacturer_id == _manufacturers.c.id)
        .values(manufacturer=_manufacturers.c.name)
    )
    op.drop_constraint(
        op.f("fk_motorbikes_manufacturer_id_manufacturers"), "motorbikes", type_="foreignkey"
    )
    op.drop_index(op.f("ix_motorbikes_manufacturer_id"), table_name="motorbikes")
    op.drop_column("motorbikes", "manufacturer_id")
    op.drop_table("manufacturers")


def _backfill_manufacturers() -> None:
    """Turn the legacy strings into rows and point the catalogue at them.

    Grouping happens on the slug, not on the raw string: two rows spelling the
    same brand differently ("BMW " and "bmw") must end up on one manufacturer,
    or the unique slug would reject the second insert.
    """
    connection = op.get_bind()
    legacy_rows = connection.execute(
        sa.select(_motorbikes.c.id, _motorbikes.c.manufacturer).where(
            _motorbikes.c.manufacturer.is_not(None)
        )
    ).all()

    brands: dict[str, _Brand] = {}
    for motorbike_id, legacy_name in legacy_rows:
        # Same normalisation as `manufacturer_service.normalize_name`.
        name = " ".join(legacy_name.split())[:NAME_LENGTH]
        slug = _NON_SLUG_CHARACTERS.sub("-", name.lower()).strip("-")
        if not slug:
            # Nothing identifiable — the string is dropped with the column.
            continue
        brand = brands.setdefault(slug, _Brand(id=str(ULID()), name=name, slug=slug))
        brand.motorbike_ids.append(motorbike_id)

    for brand in brands.values():
        connection.execute(
            _manufacturers.insert().values(id=brand.id, name=brand.name, slug=brand.slug)
        )
        for motorbike_id in brand.motorbike_ids:
            connection.execute(
                _motorbikes.update()
                .where(_motorbikes.c.id == motorbike_id)
                .values(manufacturer_id=brand.id)
            )
