"""add operations table

Progress of the background jobs, as the admin UI reads it.

Autogenerated, then hand-reviewed exactly as `4ea01933a43b` was: the `id`
column was moved to the front (autogenerate appends mixin columns), and the
downgrade drops the `operation_status` enum type explicitly — `create_table`
creates it implicitly but `drop_table` leaves it behind, which makes
re-applying this revision fail with "type ... already exists".

Revision ID: a35f16edce83
Revises: 4ea01933a43b
Create Date: 2026-08-26 20:11:26.838611

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a35f16edce83"
down_revision: str | Sequence[str] | None = "4ea01933a43b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OPERATION_STATUS_ENUM_NAME = "operation_status"


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "operations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                name=OPERATION_STATUS_ENUM_NAME,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("message", sa.String(length=512), nullable=True),
        sa.Column("error", sa.String(length=2048), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=26), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
    )
    op.create_index(
        op.f("ix_operations_entity_type_entity_id"),
        "operations",
        ["entity_type", "entity_id"],
        unique=False,
    )


def downgrade() -> None:
    """Revert this revision."""
    op.drop_index(op.f("ix_operations_entity_type_entity_id"), table_name="operations")
    op.drop_table("operations")
    # Hand-added: the enum type outlives the table that created it.
    sa.Enum(name=OPERATION_STATUS_ENUM_NAME).drop(op.get_bind())
