"""The SRD 5.1 option data a player picks a character from -- races,
skills, alignments, armour, weapons and gear (classes are `classes.py`,
WI2). Hand-authored Python literals copied from `backend/content/srd/v1/
SRD_CC_v5.1.md` at the line numbers given in the work item; no loader, no
I/O.

Point buy (`POINT_BUY`) is not in the SRD -- it is this project's own house
rule for turning six chosen scores into a balanced set."""

from .schemas import Alignment, Armour, GearItem, PointBuy, Race, Skill, Weapon

RACES: list[Race] = [
    Race(
        name="Dragonborn",
        ability_bonuses={"strength": 2, "charisma": 1},
        speed=30,
        size="Medium",
    ),
    Race(
        name="Dwarf",
        ability_bonuses={"constitution": 2},
        speed=25,
        size="Medium",
    ),
    Race(
        name="Elf",
        ability_bonuses={"dexterity": 2},
        speed=30,
        size="Medium",
    ),
    Race(
        name="Gnome",
        ability_bonuses={"intelligence": 2},
        speed=25,
        size="Small",
    ),
    Race(
        name="Half-Elf",
        ability_bonuses={"charisma": 2},
        free_ability_bonuses=2,
        speed=30,
        size="Medium",
    ),
    Race(
        name="Half-Orc",
        ability_bonuses={"strength": 2, "constitution": 1},
        speed=30,
        size="Medium",
    ),
    Race(
        name="Halfling",
        ability_bonuses={"dexterity": 2},
        speed=25,
        size="Small",
    ),
    Race(
        name="Human",
        ability_bonuses={
            "strength": 1,
            "dexterity": 1,
            "constitution": 1,
            "intelligence": 1,
            "wisdom": 1,
            "charisma": 1,
        },
        speed=30,
        size="Medium",
    ),
    Race(
        name="Tiefling",
        ability_bonuses={"intelligence": 1, "charisma": 2},
        speed=30,
        size="Medium",
    ),
]

SKILLS: list[Skill] = [
    Skill(name="Athletics", ability="strength"),
    Skill(name="Acrobatics", ability="dexterity"),
    Skill(name="Sleight of Hand", ability="dexterity"),
    Skill(name="Stealth", ability="dexterity"),
    Skill(name="Arcana", ability="intelligence"),
    Skill(name="History", ability="intelligence"),
    Skill(name="Investigation", ability="intelligence"),
    Skill(name="Nature", ability="intelligence"),
    Skill(name="Religion", ability="intelligence"),
    Skill(name="Animal Handling", ability="wisdom"),
    Skill(name="Insight", ability="wisdom"),
    Skill(name="Medicine", ability="wisdom"),
    Skill(name="Perception", ability="wisdom"),
    Skill(name="Survival", ability="wisdom"),
    Skill(name="Deception", ability="charisma"),
    Skill(name="Intimidation", ability="charisma"),
    Skill(name="Performance", ability="charisma"),
    Skill(name="Persuasion", ability="charisma"),
]

ALIGNMENTS: list[Alignment] = [
    Alignment(name="Lawful Good", abbreviation="LG"),
    Alignment(name="Neutral Good", abbreviation="NG"),
    Alignment(name="Chaotic Good", abbreviation="CG"),
    Alignment(name="Lawful Neutral", abbreviation="LN"),
    Alignment(name="Neutral", abbreviation="N"),
    Alignment(name="Chaotic Neutral", abbreviation="CN"),
    Alignment(name="Lawful Evil", abbreviation="LE"),
    Alignment(name="Neutral Evil", abbreviation="NE"),
    Alignment(name="Chaotic Evil", abbreviation="CE"),
]

# `leather-armor` (not `leather`): `classes.py` (WI2) references it as the
# equipment bullets spell it ("leather armor"), matching that convention.
ARMOURS: list[Armour] = [
    Armour(
        id="padded",
        name="Padded",
        category="light",
        base_ac=11,
        dex_bonus="full",
        strength_requirement=None,
        stealth_disadvantage=True,
    ),
    Armour(
        id="leather-armor",
        name="Leather",
        category="light",
        base_ac=11,
        dex_bonus="full",
        strength_requirement=None,
        stealth_disadvantage=False,
    ),
    Armour(
        id="studded-leather",
        name="Studded Leather",
        category="light",
        base_ac=12,
        dex_bonus="full",
        strength_requirement=None,
        stealth_disadvantage=False,
    ),
    Armour(
        id="hide",
        name="Hide",
        category="medium",
        base_ac=12,
        dex_bonus="max2",
        strength_requirement=None,
        stealth_disadvantage=False,
    ),
    Armour(
        id="chain-shirt",
        name="Chain Shirt",
        category="medium",
        base_ac=13,
        dex_bonus="max2",
        strength_requirement=None,
        stealth_disadvantage=False,
    ),
    Armour(
        id="scale-mail",
        name="Scale Mail",
        category="medium",
        base_ac=14,
        dex_bonus="max2",
        strength_requirement=None,
        stealth_disadvantage=True,
    ),
    Armour(
        id="breastplate",
        name="Breastplate",
        category="medium",
        base_ac=14,
        dex_bonus="max2",
        strength_requirement=None,
        stealth_disadvantage=False,
    ),
    Armour(
        id="half-plate",
        name="Half Plate",
        category="medium",
        base_ac=15,
        dex_bonus="max2",
        strength_requirement=None,
        stealth_disadvantage=True,
    ),
    Armour(
        id="ring-mail",
        name="Ring Mail",
        category="heavy",
        base_ac=14,
        dex_bonus="none",
        strength_requirement=None,
        stealth_disadvantage=True,
    ),
    Armour(
        id="chain-mail",
        name="Chain Mail",
        category="heavy",
        base_ac=16,
        dex_bonus="none",
        strength_requirement=13,
        stealth_disadvantage=True,
    ),
    Armour(
        id="splint",
        name="Splint",
        category="heavy",
        base_ac=17,
        dex_bonus="none",
        strength_requirement=15,
        stealth_disadvantage=True,
    ),
    Armour(
        id="plate",
        name="Plate",
        category="heavy",
        base_ac=18,
        dex_bonus="none",
        strength_requirement=15,
        stealth_disadvantage=True,
    ),
    Armour(
        id="shield",
        name="Shield",
        category="shield",
        base_ac=2,
        dex_bonus="none",
        strength_requirement=None,
        stealth_disadvantage=False,
    ),
]

WEAPONS: list[Weapon] = [
    # Simple Melee
    Weapon(
        id="club",
        name="Club",
        proficiency="simple",
        ranged=False,
        damage_die="1d4",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="dagger",
        name="Dagger",
        proficiency="simple",
        ranged=False,
        damage_die="1d4",
        damage_type="piercing",
        finesse=True,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="greatclub",
        name="Greatclub",
        proficiency="simple",
        ranged=False,
        damage_die="1d8",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="handaxe",
        name="Handaxe",
        proficiency="simple",
        ranged=False,
        damage_die="1d6",
        damage_type="slashing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="javelin",
        name="Javelin",
        proficiency="simple",
        ranged=False,
        damage_die="1d6",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="light-hammer",
        name="Light Hammer",
        proficiency="simple",
        ranged=False,
        damage_die="1d4",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="mace",
        name="Mace",
        proficiency="simple",
        ranged=False,
        damage_die="1d6",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="quarterstaff",
        name="Quarterstaff",
        proficiency="simple",
        ranged=False,
        damage_die="1d6",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die="1d8",
    ),
    Weapon(
        id="sickle",
        name="Sickle",
        proficiency="simple",
        ranged=False,
        damage_die="1d4",
        damage_type="slashing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="spear",
        name="Spear",
        proficiency="simple",
        ranged=False,
        damage_die="1d6",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die="1d8",
    ),
    # Simple Ranged
    Weapon(
        id="light-crossbow",
        name="Light Crossbow",
        proficiency="simple",
        ranged=True,
        damage_die="1d8",
        damage_type="piercing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="dart",
        name="Dart",
        proficiency="simple",
        ranged=True,
        damage_die="1d4",
        damage_type="piercing",
        finesse=True,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="shortbow",
        name="Shortbow",
        proficiency="simple",
        ranged=True,
        damage_die="1d6",
        damage_type="piercing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="sling",
        name="Sling",
        proficiency="simple",
        ranged=True,
        damage_die="1d4",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    # Martial Melee
    Weapon(
        id="battleaxe",
        name="Battleaxe",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="slashing",
        finesse=False,
        two_handed=False,
        versatile_die="1d10",
    ),
    Weapon(
        id="flail",
        name="Flail",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="glaive",
        name="Glaive",
        proficiency="martial",
        ranged=False,
        damage_die="1d10",
        damage_type="slashing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="greataxe",
        name="Greataxe",
        proficiency="martial",
        ranged=False,
        damage_die="1d12",
        damage_type="slashing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="greatsword",
        name="Greatsword",
        proficiency="martial",
        ranged=False,
        damage_die="2d6",
        damage_type="slashing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="halberd",
        name="Halberd",
        proficiency="martial",
        ranged=False,
        damage_die="1d10",
        damage_type="slashing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="lance",
        name="Lance",
        proficiency="martial",
        ranged=False,
        damage_die="1d12",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="longsword",
        name="Longsword",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="slashing",
        finesse=False,
        two_handed=False,
        versatile_die="1d10",
    ),
    Weapon(
        id="maul",
        name="Maul",
        proficiency="martial",
        ranged=False,
        damage_die="2d6",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="morningstar",
        name="Morningstar",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="pike",
        name="Pike",
        proficiency="martial",
        ranged=False,
        damage_die="1d10",
        damage_type="piercing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="rapier",
        name="Rapier",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="piercing",
        finesse=True,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="scimitar",
        name="Scimitar",
        proficiency="martial",
        ranged=False,
        damage_die="1d6",
        damage_type="slashing",
        finesse=True,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="shortsword",
        name="Shortsword",
        proficiency="martial",
        ranged=False,
        damage_die="1d6",
        damage_type="piercing",
        finesse=True,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="trident",
        name="Trident",
        proficiency="martial",
        ranged=False,
        damage_die="1d6",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die="1d8",
    ),
    Weapon(
        id="war-pick",
        name="War Pick",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="warhammer",
        name="Warhammer",
        proficiency="martial",
        ranged=False,
        damage_die="1d8",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die="1d10",
    ),
    Weapon(
        id="whip",
        name="Whip",
        proficiency="martial",
        ranged=False,
        damage_die="1d4",
        damage_type="slashing",
        finesse=True,
        two_handed=False,
        versatile_die=None,
    ),
    # Martial Ranged
    Weapon(
        id="blowgun",
        name="Blowgun",
        proficiency="martial",
        ranged=True,
        damage_die="1",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="hand-crossbow",
        name="Hand Crossbow",
        proficiency="martial",
        ranged=True,
        damage_die="1d6",
        damage_type="piercing",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
    Weapon(
        id="heavy-crossbow",
        name="Heavy Crossbow",
        proficiency="martial",
        ranged=True,
        damage_die="1d10",
        damage_type="piercing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    Weapon(
        id="longbow",
        name="Longbow",
        proficiency="martial",
        ranged=True,
        damage_die="1d8",
        damage_type="piercing",
        finesse=False,
        two_handed=True,
        versatile_die=None,
    ),
    # Net deals no damage in the SRD (its entry is "--"); modelled as a
    # zero bludgeoning die since `damage_type` has no "none" option.
    Weapon(
        id="net",
        name="Net",
        proficiency="martial",
        ranged=True,
        damage_die="0",
        damage_type="bludgeoning",
        finesse=False,
        two_handed=False,
        versatile_die=None,
    ),
]

GEAR: list[GearItem] = [
    GearItem(
        id="burglars-pack",
        name="Burglar's Pack",
        description=(
            "Includes a backpack, a bag of 1,000 ball bearings, 10 feet of "
            "string, a bell, 5 candles, a crowbar, a hammer, 10 pitons, a "
            "hooded lantern, 2 flasks of oil, 5 days rations, a tinderbox, "
            "and a waterskin. The pack also has 50 feet of hempen rope "
            "strapped to the side of it."
        ),
    ),
    GearItem(
        id="diplomats-pack",
        name="Diplomat's Pack",
        description=(
            "Includes a chest, 2 cases for maps and scrolls, a set of fine "
            "clothes, a bottle of ink, an ink pen, a lamp, 2 flasks of oil, "
            "5 sheets of paper, a vial of perfume, sealing wax, and soap."
        ),
    ),
    GearItem(
        id="dungeoneers-pack",
        name="Dungeoneer's Pack",
        description=(
            "Includes a backpack, a crowbar, a hammer, 10 pitons, 10 "
            "torches, a tinderbox, 10 days of rations, and a waterskin. "
            "The pack also has 50 feet of hempen rope strapped to the "
            "side of it."
        ),
    ),
    GearItem(
        id="entertainers-pack",
        name="Entertainer's Pack",
        description=(
            "Includes a backpack, a bedroll, 2 costumes, 5 candles, 5 days "
            "of rations, a waterskin, and a disguise kit."
        ),
    ),
    GearItem(
        id="explorers-pack",
        name="Explorer's Pack",
        description=(
            "Includes a backpack, a bedroll, a mess kit, a tinderbox, 10 "
            "torches, 10 days of rations, and a waterskin. The pack also "
            "has 50 feet of hempen rope strapped to the side of it."
        ),
    ),
    GearItem(
        id="priests-pack",
        name="Priest's Pack",
        description=(
            "Includes a backpack, a blanket, 10 candles, a tinderbox, an "
            "alms box, 2 blocks of incense, a censer, vestments, 2 days of "
            "rations, and a waterskin."
        ),
    ),
    GearItem(
        id="scholars-pack",
        name="Scholar's Pack",
        description=(
            "Includes a backpack, a book of lore, a bottle of ink, an ink "
            "pen, 10 sheets of parchment, a little bag of sand, and a "
            "small knife."
        ),
    ),
    GearItem(id="crossbow-bolts", name="Crossbow Bolts"),
    GearItem(id="arrows", name="Arrows"),
    GearItem(id="thieves-tools", name="Thieves' Tools"),
    GearItem(id="musical-instrument", name="Musical Instrument"),
    GearItem(id="arcane-focus", name="Arcane Focus"),
    GearItem(id="component-pouch", name="Component Pouch"),
    GearItem(id="druidic-focus", name="Druidic Focus"),
    GearItem(id="holy-symbol", name="Holy Symbol"),
    GearItem(id="spellbook", name="Spellbook"),
]

POINT_BUY = PointBuy(
    costs={8: 0, 9: 1, 10: 2, 11: 3, 12: 4, 13: 5, 14: 7, 15: 9},
    budget=27,
    minimum=8,
    maximum=15,
)
